//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddtoCart {
            get {
                return ResourceManager.GetString("AddtoCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllSpecials.
        /// </summary>
        public static string AllSpecials {
            get {
                return ResourceManager.GetString("AllSpecials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Special Electrical Devices.
        /// </summary>
        public static string AllSpecialsElectricals {
            get {
                return ResourceManager.GetString("AllSpecialsElectricals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Special Meats.
        /// </summary>
        public static string AllSpecialsMeats {
            get {
                return ResourceManager.GetString("AllSpecialsMeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beef.
        /// </summary>
        public static string Beef {
            get {
                return ResourceManager.GetString("Beef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Details.
        /// </summary>
        public static string CarDetail {
            get {
                return ResourceManager.GetString("CarDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Products.
        /// </summary>
        public static string CartProduct {
            get {
                return ResourceManager.GetString("CartProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Recorder.
        /// </summary>
        public static string CDRecorder {
            get {
                return ResourceManager.GetString("CDRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckOut.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken.
        /// </summary>
        public static string Chicken {
            get {
                return ResourceManager.GetString("Chicken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Confirmnewpassword {
            get {
                return ResourceManager.GetString("Confirmnewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match.
        /// </summary>
        public static string ConfirmnewpasswordError {
            get {
                return ResourceManager.GetString("ConfirmnewpasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Shopping.
        /// </summary>
        public static string ContinueShopping {
            get {
                return ResourceManager.GetString("ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Credit Card Number is required.
        /// </summary>
        public static string CreditCardNumberRequired {
            get {
                return ResourceManager.GetString("CreditCardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuban Shop. All Rights Reserved 2016.
        /// </summary>
        public static string CubanShop {
            get {
                return ResourceManager.GetString("CubanShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Currentpassword {
            get {
                return ResourceManager.GetString("Currentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password does not match.
        /// </summary>
        public static string CurrentPasswordError {
            get {
                return ResourceManager.GetString("CurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete One.
        /// </summary>
        public static string DeleteOne {
            get {
                return ResourceManager.GetString("DeleteOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delivery Address is required.
        /// </summary>
        public static string DeliveryAddressRequired {
            get {
                return ResourceManager.GetString("DeliveryAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Details.
        /// </summary>
        public static string ElectricalDetails {
            get {
                return ResourceManager.GetString("ElectricalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Devices.
        /// </summary>
        public static string ElectricalDevice {
            get {
                return ResourceManager.GetString("ElectricalDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending CheckOut.
        /// </summary>
        public static string EndingCheckOut {
            get {
                return ResourceManager.GetString("EndingCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Data.
        /// </summary>
        public static string FilterData {
            get {
                return ResourceManager.GetString("FilterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is Required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Order.
        /// </summary>
        public static string forOrder {
            get {
                return ResourceManager.GetString("forOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have an account.
        /// </summary>
        public static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat Details.
        /// </summary>
        public static string MeatDetails {
            get {
                return ResourceManager.GetString("MeatDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meats.
        /// </summary>
        public static string Meats {
            get {
                return ResourceManager.GetString("Meats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer.
        /// </summary>
        public static string Mixer {
            get {
                return ResourceManager.GetString("Mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutton.
        /// </summary>
        public static string Mutton {
            get {
                return ResourceManager.GetString("Mutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Newpassword {
            get {
                return ResourceManager.GetString("Newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not any order for this date.
        /// </summary>
        public static string OrderUser {
            get {
                return ResourceManager.GetString("OrderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string PasswordCompare {
            get {
                return ResourceManager.GetString("PasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password must be at least 6 characters long.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pork.
        /// </summary>
        public static string Pork {
            get {
                return ResourceManager.GetString("Pork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        public static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Seek {
            get {
                return ResourceManager.GetString("Seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find all our special electrical appliances.
        /// </summary>
        public static string SpecialElectricalDetails {
            get {
                return ResourceManager.GetString("SpecialElectricalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Electrical Devices.
        /// </summary>
        public static string SpecialElectricalDevices {
            get {
                return ResourceManager.GetString("SpecialElectricalDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find all our special meats.
        /// </summary>
        public static string SpecialMeatDetails {
            get {
                return ResourceManager.GetString("SpecialMeatDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Meat Products.
        /// </summary>
        public static string SpecialMeatProducts {
            get {
                return ResourceManager.GetString("SpecialMeatProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Products.
        /// </summary>
        public static string SpecialProducts {
            get {
                return ResourceManager.GetString("SpecialProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        public static string Specials {
            get {
                return ResourceManager.GetString("Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tape Recorder.
        /// </summary>
        public static string TapeRecorder {
            get {
                return ResourceManager.GetString("TapeRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veal.
        /// </summary>
        public static string Veal {
            get {
                return ResourceManager.GetString("Veal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart.
        /// </summary>
        public static string ViewCart {
            get {
                return ResourceManager.GetString("ViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not Electrical Device in the Shop.
        /// </summary>
        public static string WithoutElectrical {
            get {
                return ResourceManager.GetString("WithoutElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not Meat in the Shop.
        /// </summary>
        public static string WithoutMeat {
            get {
                return ResourceManager.GetString("WithoutMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart do not have products..
        /// </summary>
        public static string WithoutProduct {
            get {
                return ResourceManager.GetString("WithoutProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Data.
        /// </summary>
        public static string YourData {
            get {
                return ResourceManager.GetString("YourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Order.
        /// </summary>
        public static string YourOrder {
            get {
                return ResourceManager.GetString("YourOrder", resourceCulture);
            }
        }
    }
}
